version: "2"
linters:
  default: none
  enable:
    - bidichk
    - copyloopvar
    - decorder
    - dogsled
    - durationcheck
    - errcheck
    - forcetypeassert
    - funlen
    - goconst
    - godot
    - godox
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usetesting
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
        source: ^func Test
      - linters:
          - funlen
        source: ^func NewRootCommand
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
